### PR TITLE
issue #2

### PR DESCRIPTION
**Pull request by nandofromthebando**
Added e2e program that passes the source_code_preserve_tests.py

### CODE REVIEW

**Comment by shairubin** [comment]
thank you 
indeed the program looks good
in order to this program to run as part of the test program you need to add its name to this file:
source_code_preserve_tests.py
see line 48
then you need to run the main and see that it ends successfully. 

would be happy to provide more guidance if needed

**Comment by nandofromthebando** [comment]
Ok will do thank you!

**Comment by nandofromthebando** [comment]
I updated it let me know if this works!

**Comment by nandofromthebando** [comment]
also attempted as resolution #1 let me know if this works as well!

**Comment by shairubin** [comment]
hello
1. please note that the isprime program produces incorrect results:
1 is a Prime Number
2 is a not Prime Number
3 is a not Prime Number
**4 is a Prime Number**
5 is a not Prime Number
**6 is a Prime Number**
7 is a not Prime Number
**8 is a Prime Number
9 is a Prime Number
10 is a Prime Number**
11 is a not Prime Number
12 is a Prime Number
13 is a not Prime Number
14 is a Prime Number

Process finished with exit code 0
2. In order to accept this pull request -- you actually need to provide a correct program 
3. Also -- we cannot accept a pull request that addresses 2 issues. please delete the other two files and create ANOTHER pull request for the other issue.

**Comment by nandofromthebando** [comment]
I fixed prime.py it is working correctly I'm sorry, I'll delete the other PR and submit it after you close this one sorry.

**Comment by nandofromthebando** [comment]
Removed the other issue and I can push it separately after you merge this one. Sorry for the confusion!

**Pull request merged**
